# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

basinCpp <- function(dm2, bsn, dun) {
    .Call(`_mesoclim_basinCpp`, dm2, bsn, dun)
}

renumberbasin <- function(m, u) {
    .Call(`_mesoclim_renumberbasin`, m, u)
}

#'
#' This function returns a numeric matrix identifying
#' matching values from a raster that intersect with
#' a set of points
#' @export
invls_calc <- function(lsm, resolution, xmin, ymax, s, direction, slr, slr_xmin, slr_xmax, slr_ymin, slr_ymax) {
    .Call(`_mesoclim_invls_calc`, lsm, resolution, xmin, ymax, s, direction, slr, slr_xmin, slr_xmax, slr_ymin, slr_ymax)
}

rainadjustv <- function(rain, rrain, rfrac, rtot) {
    .Call(`_mesoclim_rainadjustv`, rain, rrain, rfrac, rtot)
}

rainadjustm <- function(rainm, rrain, rfrac, rtot) {
    .Call(`_mesoclim_rainadjustm`, rainm, rrain, rfrac, rtot)
}

