# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

basinCpp <- function(dm2, bsn, dun) {
    .Call(`_mesoclim_basinCpp`, dm2, bsn, dun)
}

renumberbasin <- function(m, u) {
    .Call(`_mesoclim_renumberbasin`, m, u)
}

